services:
  - type: web
    name: limkokwing-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: your_mysql_password
      - key: DB_NAME
        value: limkokwing_system

  - type: web
    name: florah-frontend
    env: node
    buildCommand: cd florah && npm install && npm run build
    startCommand: cd florah && serve -s build
    staticPublishPath: florah/build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://limkokwing-backend.onrender.com
